# LLM App Project Configuration

# Model Configuration
models:
  application:
    provider: "vertex"
    parameters:
      model: "gemini-1.5-flash"
      temperature: 1
      max_tokens: 2048
      top_p: 1.0

