# LLM App Project Configuration

# Model Configuration
models:
  application:
    provider: "openai"
    parameters:
      model: "gpt-4o-mini"
      temperature: 1
      max_tokens: 2048
      top_p: 1.0

